name: Workflow Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions workflow lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: actionlint実行
        uses: reviewdog/action-actionlint@v1
